name: urlaubsbilder_galerie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Aegypten/
    - assets/Dom.Rep./
    - assets/Gran Canaria/
    - assets/Malediven/
    - assets/Malle/
    - assets/Mexico/
    - assets/Thailand/ 
    - assets/Tuerkei/ 
    - assets/Oesterreich/
    - assets/Kreuzfahrt/
    - assets/Kroatien/
    - assets/Mosel/
    - assets/Toscana/
